GET http://localhost:5066/api/games

###
GET http://localhost:5066/api/games/1

###
POST  http://localhost:5066/api/games
Content-Type: application/json

{
    "name": "GTA V",
    "genreIds": [3,2],
    "platform": "PS4",
    "releaseDate": "2013-09-17"

}

###
PUT  http://localhost:5066/api/games/15
Content-Type: application/json

{
    "name": "Cyberpuasdnk 2077",
    "genreId": 3,
    "platform": "PC",
    "releaseDate": "2020-12-10"

}

###
DELETE  http://localhost:5066/api/games/15