GET http://localhost:5066/api/games

###
GET http://localhost:5066/api/games/9

###
POST  http://localhost:5066/api/games
Content-Type: application/json

{
    "name": "GTA V",
    "genre": "Action",
    "platform": "PS4",
    "releaseDate": "2013-09-17"

}

###
PUT  http://localhost:5066/api/games/9
Content-Type: application/json

{
    "name": "Cyberpuasdnk 2077",
    "genre": "RPG",
    "platform": "PC",
    "releaseDate": "2020-12-10"

}

###
DELETE  http://localhost:5066/api/games/9